### ISSUE TITLE
Questions about repetitions and N_e values in momi2

### ISSUE THREAD

**Issue by SergioB1983** [popgenmethods/momi2#13]
Hi,

I am using `momi` to estimate possible demographic scenarios, and I am doing some tests to with one species whit 3 populations (one species of Passeriformes and using Ultraconserved Elements, UCEs). I have two questions about the configuration of the models.

1. To create the model it is possible estimate the `N_e` values like the other parameters (e.g divergence time)? Or it's necessary define this value from the beginning? I try multiple `N_e` values, and the results are very variable (mainly to estimate divergence times). So, I wondering if there is a approach to estimate this parameter within the model?

2. Also, I want to do a x number of repetitions to choice the best run for each model (similar to `fastsimcoal2`)). I am running this (tutotial of `momi`):

```
results = []
n_runs = 3
for i in range(n_runs):
    print(f"Starting run {i+1} out of {n_runs}...")
    add_pulse_model.set_params(
        # parameters inherited from no_pulse_model are set to their previous values
        no_pulse_model.get_params(),
        # other parmaeters are set to random initial values
        randomize=True)

    results.append(add_pulse_model.optimize(options={"maxiter":200}))

# sort results according to log likelihood, pick the best one
best_result = sorted(results, key=lambda r: r.log_likelihood)[0]

add_pulse_model.set_params(best_result.parameters)
best_result
```

However, all the runs are virtually the same result. How I can avoid this situation?

I review the tutorial of `momi` and the web of the RadCamp 2018 in SP, Brazil, but I dont know how resolve these points.

Thanks in advance.

**Comment by jackkamm** [comment]
Sorry for never responding to this. I am closing the issue because it is very old now.

Regarding your first question about N_e, the `N_e` parameter passed to `DemographicModel` should be thought of as a constant scaling factor rather than a parameter to be estimated. If you wish to estimate the effective size of some population(s), you should add a parameter for it to the model with `add_size_param`, and then set your populations to have that size when creating them with `add_leaf`.
