### ISSUE TITLE
Document add_pulse_param() using a function

### ISSUE THREAD

**Issue by isaacovercast** [popgenmethods/momi2#14]
This is in reference to the idea of adding multiple pulse events evenly spaced to better approximate a continuous migration model. I can see that both add_pulse_param() and add_time_param() have `rgen` arguments which look like they could be used for something like this, but it isn't immediately apparent to me how it would work. Even a gist with example code for how to apply it would be great! Thanks again Jack for dropping in on our ECEM meeting the other day, it was super helpful!

**Comment by jackkamm** [comment]
This can be achieved as follows:  
```
model.move_lineages(pop1, pop2, t=lambda params: params.t_div / 2)
 ```
The lambda function should take a single argument, "params", which has all the defined parameters as attributes, e.g. "params.t_div" if you have defined a "t_div" parameter.

Passing functions instead of parameters also works for the other demographic events like `set_size()` and `add_leaf()`.

Some care is needed -- momi internally uses autograd to compute gradients, so the function must be differentiable by autograd. Lambda functions to do simple arithmetic (as above) are fine, however more complex functions with variable assignments, or that call external methods, need some care, otherwise gradients will be wrong. The autograd [tutorial](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md) has some info here.

Leaving this issue open until I can fully document this feature in the manual.

**Comment by lucasrocmoreira** [comment]
Thanks, Jack. This is very helpful.

**Comment by grafau** [comment]
That looks very useful, could you please comment, for newbies such as myself, how to implement it? I understand that lambda functions could give you "evenly spaced time points". So then, one would model it as:
move.linages("POP1", "POP2", t ="t_div")
move.linages("POP1", "POP2",t =lambda params: params.t_div - 500, p = "p_ad1")
move.linages("POP1", "POP2",t =lambda params: params.t_div - 1000, p = "p_ad2")
etc?

Many thanks for your help!

**Comment by jackkamm** [comment]
Hi @grafau,

The problem with your example, is that if the length of the branch gets less to 1000, then your lambda function will return an invalid time.

Thus, rather than adding pulses at fixed offsets, I prefer to add them at evenly spaced offsets, using division rather than subtraction. So your example would be like:
```
move.linages("POP1", "POP2", t ="t_div")
move.linages("POP1", "POP2",t =lambda params: params.t_div * 2 / 3, p = "p_ad1")
move.linages("POP1", "POP2",t =lambda params: params.t_div * 1 / 3, p = "p_ad2")
```
Assuming that POP1 and POP2 both start at time 0. More generally, if POP1 starts at t_pop1 and POP2 starts at t_pop2, I might do:
```
import autograd.numpy as anp
move.linages("POP1", "POP2", t ="t_div")
move.linages("POP1", "POP2",t =lambda params: (params.t_div -  anp.max(params.t_pop1, params.t_pop2) * 2 / 3, p = "p_ad1")
etc
```
Notice I used the `max` function from `autograd.numpy` instead of the usual max. Basically, `momi2` uses `autograd` to compute gradients, so all math functions must be taken from autograd. See the autograd tutorial for more details how to write autograd-compatible code: https://github.com/HIPS/autograd/blob/master/docs/tutorial.md

**Comment by jackkamm** [comment]
Yes, that looks like it would be fine.

**Comment by jackkamm** [comment]
I've added documentation for this feature here:
https://momi2.readthedocs.io/en/latest/tutorial.html#Using-functions-of-model-parameters-as-demographic-parameters
