### ISSUE TITLE
Installation using conda

### ISSUE THREAD

**Issue by yss1** [popgenmethods/momi2#4]
Installation using conda requires python 3.6 or higher.   Here is the error message I get when using python 3.5.

---
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - momi -> python >=3.6,<3.7.0a0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by jackkamm** [comment]
I think there is some dependency hell happening due to using both the conda-forge and bioconda channels. Can you see if the following works:
```
conda install momi -c jackkamm -c conda-forge -c bioconda
```
that is, switching the order of bioconda and conda-forge in the install instructions, which I think will give priority to conda-forge.

You may need to add `python=3.5` to ensure you are testing python3.5 instead of 3.6:
```
conda install momi python=3.5 -c jackkamm -c conda-forge -c bioconda
```

Right now conda-forge is needed for `msprime` and bioconda is needed for `pysam`. I think I will package `pysam` for conda-forge to avoid the need for bioconda. In the meantime let me know if the above works.

**Comment by jackkamm** [comment]
Hmm, that's annoying, installing with Python 3.5 works for me. I am using miniconda though so maybe that's the difference, will test with anaconda.

The install process is clearly too complicated right now though. Maybe would be simpler to put binary builds on PyPi and stop using conda, though this has its own downsides (dependencies msprime and pysam install more smoothly on conda than pip). Will leave this issue open until I figure this out.

**Comment by terhorst** [comment]
I recommend avoiding the conda-forge dependency if possible. I had a
similar issue arise with SMC++, and was told that mixing conda and
conda-forge packages is not supported and could lead to bugs.
(conda/conda/6030)

**Comment by yss1** [comment]
Another thing to note is that the command "source activate momi-env" works only in bash shell.

**Comment by terhorst** [comment]
@jackkamm You can also upload Conda binaries to anaconda.org. I do this for SMC++ using Travis and it works very well.

**Comment by jackkamm** [comment]
@terhorst do you mean uploading the Conda binary to a personal channel on anaconda.org? I already do this (though not yet with travis). Or do you mean uploading to the main defaults channel?

Still haven't figured out a clean way to package/distribute. Dependency `msprime` is only on conda-forge channel, while dependency `pysam` is only on bioconda channel. Both msprime and pysam are on pypi, but pure pypi distribution is bad for OSX users because I have no way to ensure they have libomp.

Looks like for smc++ you are requiring users to pull dependencies from both bioconda and conda-forge so I guess you weren't able to rid that dependency either?

Closest I came to reproducing @yss1 's error, it seems like the dependency hell was caused by bioconda, but I'm still not 100% sure about it. Maybe the cleanest solution would be to have users install as little as possible from bioconda/conda-forge, like:
```
conda install msprime -c conda-forge
conda install pysam -c bioconda
conda install momi -c jackkamm # install all other dependencies from defaults
```

**Comment by jackkamm** [comment]
@yss1 unable to reproduce this on anaconda python3.5 environment. After investigation I think this is not to do with python3.5/bioconda/conda-forge but rather using old version of conda/anaconda. Please let me know if you can reproduce on a newer anaconda, then I will re-open
