### ISSUE TITLE
Advice on modelling one pop over time.

### ISSUE THREAD

**Issue by Hjorvik** [popgenmethods/momi2#67]
Hi! I'm trying to define a model for a population with several samples over time (10.000 to 1700 BP) that has experienced several admixture events from different sources. Would be wise to set all samples as the same population and add the pulses, or should I add a leaf per ancient sample/period and add the pulses to the corresponding branch?

**Comment by jackkamm** [comment]
You'll need to specify a separate leaf pop per period, so that samples from separate time points don't belong to the same entry in the SFS.

You can just have the leaves immediately merge onto the "main" population prior to the sample time, if the samples are all from the same population over time.

On the other hand, if you have some prior knowledge about the substructure of your population, maybe you will want to have the leaves extend for some period of time, and have the pulses go into those branches instead.

The better modeling choice will depend on the details of your data.

**Comment by Hjorvik** [comment]
The thing is that this population belongs to just one site, so there is no significative structure. I'll follow your advice and merge them period by period. It's going to be an interesting model to optimize.

Thanks for the answer!
